force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Store_In_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Store_In_Out_Time__c</fullName>
    <description>For Store Sign In or Sign Out Time.</description>
    <label>Store In/Out Time</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AttendanceCheckScheduler.cls
global class AttendanceCheckScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {
        Integer currentDay = Date.today().day();
        String currentDayString = 'Day_' + String.valueOf(currentDay) + '__c';
        String query = 'SELECT Id, Name, Store_In_Out_Time__c FROM Attendance__c WHERE ' + currentDayString + ' = false';
        List<Attendance__c> attendanceList = Database.query(query);
        List<Attendance__c> attendanceListToUpdate = new List<Attendance__c>();
        for(Attendance__c att : attendanceList) {
            if(att.Store_In_Out_Time__c != null) {
                
            }
        }
    }
}